package frc.robot.misc;

/**
 * This class holds all the trajectories used in auto.
 * As trajectory generation can take a while, it is not practical to do these in real-time.
 * Therefore some already known trajectories are generated by this class when the robot
 * starts up.
 */
public final class AutoPaths {
    
    
    public static void generateAll() {
        
    }
}
